Repository uizaio/api-wrapper-ruby, pull requests merged in 2019-02, with the labels that each got.

#1 221606_Init
  CODE_OF_CONDUCT.md
  Gemfile
  Gemfile.lock
  LICENSE.txt
  PULL_REQUEST_TEMPLATE.md
  README.md
  Rakefile
  bin/console
  bin/setup
  lib/uiza.rb
  lib/uiza/version.rb
  spec/spec_helper.rb
  spec/uiza_spec.rb
  uiza.gemspec
Labels: IN REVIEW

#2 221606_Init_add_rubucop_and_extra_files
  .rubocop.yml
  .rubocop_todo.yml
  CHANGELOG.md
  CONTRIBUTORS.txt
  Gemfile
  Gemfile.lock
  History.txt
  LICENSE.txt
  PULL_REQUEST_TEMPLATE.md
Labels: IN REVIEW

#3 221703_Create_entity
  .rubocop.yml
  .rubocop_todo.yml
  lib/uiza.rb
  lib/uiza/api_operations/create.rb
  lib/uiza/entity.rb
  lib/uiza/uiza_client.rb
Labels: API, IN REVIEW

#5 221606_Update_rubocop
  .rubocop.yml
  .rubocop_disable.yml
  .rubocop_enable.yml
  .rubocop_todo.yml
  Rakefile
  lib/uiza/api_operations/create.rb
  lib/uiza/uiza_client.rb
  lib/uiza/version.rb
Labels: API, IN REVIEW

#6 221802_Retrieve_entity
  lib/uiza.rb
  lib/uiza/api_operations/retrieve.rb
  lib/uiza/entity.rb
  lib/uiza/uiza_client.rb
Labels: API, IN REVIEW

#10 221817_Delete_entity
  lib/uiza.rb
  lib/uiza/api_operations/delete.rb
  lib/uiza/entity.rb
  lib/uiza/uiza_client.rb
Labels: API, IN REVIEW

#18 221822_get_aws_upload_key
  README.md
  lib/uiza/entity.rb
Labels: API, DOCUMENT, IN REVIEW

#20 222474_retrieve_storage
  README.md
  lib/uiza.rb
  lib/uiza/storage.rb
Labels: API, DOCUMENT, IN REVIEW

#21 222476_storage_remove
  README.md
  lib/uiza.rb
  lib/uiza/api_operations/remove.rb
  lib/uiza/storage.rb
Labels: API, DOCUMENT, IN REVIEW

#24 222473_add_storage
  README.md
  lib/uiza.rb
  lib/uiza/api_operations/add.rb
  lib/uiza/storage.rb
Labels: API, DOCUMENT, IN REVIEW

#23 222475_storage_update
  README.md
  lib/uiza/api_operations/list.rb
  lib/uiza/storage.rb
Labels: API, DOCUMENT, IN REVIEW

#26 222782_category_create
  README.md
  lib/uiza.rb
  lib/uiza/category.rb
Labels: API, DOCUMENT, IN REVIEW

#22 222506_Init_base_code_handle_error
  lib/uiza.rb
  lib/uiza/api_operations/add.rb
  lib/uiza/api_operations/create.rb
  lib/uiza/api_operations/delete.rb
  lib/uiza/api_operations/list.rb
  lib/uiza/api_operations/remove.rb
  lib/uiza/api_operations/retrieve.rb
  lib/uiza/api_operations/update.rb
  lib/uiza/entity.rb
  lib/uiza/error/bad_request_error.rb
  lib/uiza/error/client_error.rb
  lib/uiza/error/internal_server_error.rb
  lib/uiza/error/not_found_error.rb
  lib/uiza/error/server_error.rb
  lib/uiza/error/service_unavailable_error.rb
  lib/uiza/error/uiza_error.rb
  lib/uiza/error/unauthorized_error.rb
  lib/uiza/error/unprocessable_error.rb
  lib/uiza/uiza_client.rb
Labels: IN REVIEW

#25 222628_Init_base_for_RSpec
  .rubocop_enable.yml
  Gemfile
  Gemfile.lock
  lib/uiza/error/bad_request_error.rb
  lib/uiza/error/internal_server_error.rb
  lib/uiza/error/not_found_error.rb
  lib/uiza/error/service_unavailable_error.rb
  lib/uiza/error/uiza_error.rb
  lib/uiza/error/unauthorized_error.rb
  lib/uiza/error/unprocessable_error.rb
  lib/uiza/uiza_client.rb
  spec/spec_helper.rb
  spec/uiza/entity/create_spec.rb
  spec/uiza/entity/delete_spec.rb
  spec/uiza/entity/get_aws_upload_key_spec.rb
  spec/uiza/entity/get_status_publish_spec.rb
  spec/uiza/entity/list_spec.rb
  spec/uiza/entity/publish_spec.rb
  spec/uiza/entity/retrieve_spec.rb
  spec/uiza/entity/search_spec.rb
  spec/uiza/entity/update_spec.rb
  spec/uiza/uiza_client_spec.rb
  spec/uiza_spec.rb
Labels: IN REVIEW

#36 NA_storage_add_api_description_link
  lib/uiza/storage.rb
Labels: IN REVIEW

#37 222473_storage_add_return_object
  lib/uiza/api_operation/add.rb
Labels: IN REVIEW

#38 NA_storage_change_method_format
  lib/uiza.rb
  lib/uiza/api_resource/storage_resource.rb
Labels: IN REVIEW

#40 NA_storage_rspec
  spec/uiza/storage/add_spec.rb
  spec/uiza/storage/remove_spec.rb
  spec/uiza/storage/retrieve_spec.rb
  spec/uiza/storage/update_spec.rb
Labels: IN REVIEW

#41 NA_category_add_api_decription_link_and_change_method_format
  lib/uiza.rb
  lib/uiza/api_resource/category_resource.rb
  lib/uiza/category.rb
Labels: IN REVIEW

#43 222785_category_update
  lib/uiza/api_resource/category_resource.rb
  lib/uiza/category.rb
  spec/uiza/category.rb/create_spec.rb
  spec/uiza/category.rb/retrieve_spec.rb
  spec/uiza/category.rb/update_spec.rb
Labels: IN REVIEW

#45 222786_category_delete
  lib/uiza/api_resource/category_resource.rb
  lib/uiza/category.rb
  spec/uiza/category/delete_spec.rb
Labels: IN REVIEW

#59 224319_live_list_recorded
  doc/LIVE_STREAMING.md
  lib/uiza/live.rb
  lib/uiza/uiza_client.rb
  spec/uiza/live/list_recorded_spec.rb
  spec/uiza/live/start_feed_spec.rb
Labels: IN REVIEW

#62 224856_callback_retrieve
  README.md
  doc/CALLBACK.md
  lib/uiza.rb
  lib/uiza/callback.rb
  spec/uiza/callback/retrieve_spec.rb
Labels: IN REVIEW

#66 224854_callback_create
  Gemfile
  doc/CALLBACK.md
  lib/uiza/callback.rb
  lib/uiza/uiza_open_struct.rb
  spec/uiza/callback/create_spec.rb
Labels: IN REVIEW

#68 224858_callback_delete
  doc/CALLBACK.md
  lib/uiza/callback.rb
  spec/uiza/callback/delete_spec.rb
Labels: IN REVIEW

#76 225753_user_list
  doc/USER.md
  lib/uiza/user.rb
  spec/uiza/user/list_spec.rb
Labels: IN REVIEW
